name: pathfindrnet-hg-smg-tc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pyarrow
  - pyyaml
  - shapely
  - opencv
  - pytest
  - pip:
      - ruff
      - hdbscan
